#!/bin/bash

set -eux

files=(*/Dockerfile)

build-and-push() (
  image=$(dirname $1)
  cd "$image"
  docker buildx build --pull --push --platform linux/amd64,linux/arm64 -t "wint/$image:latest" .
)

set -x
for f in "${files[@]}"; do
  build-and-push "$f"
done
