#!/bin/bash

set -eu

files=(*/Dockerfile)

echo_exec() (
  echo "$@"
  exec "$@"
)

gha_cache="url_v2=$ACTIONS_RESULTS_URL,token=$ACTIONS_RUNTIME_TOKEN"

build-and-push() (
  image=$(dirname $1)
  cd "$image"

  tag="wint/$image:latest"

  if [[ ",$SKIP_CACHE," = *",$image,"* ]] || [[ "$SKIP_CACHE" = "all" ]]; then
    nocache_opts=(--no-cache)
  else
    nocache_opts=()
  fi

  echo "::group::$tag"
  printf '>>>>>>>>>>>>>>>>>>>>>>>>>> building and pushing %s <<<<<<<<<<<<<<<<<<<<<<<<<<\n' "$tag"
  echo_exec docker buildx build \
    --pull \
    --push \
    "--cache-from=type=gha,scope=$image,$gha_cache" \
    "--cache-to=type=gha,mode=max,scope=$image,$gha_cache" \
    "${nocache_opts[@]}" \
    --platform linux/amd64,linux/arm64 \
    --sbom=false --provenance=false \
    -t "$tag" \
    .
  echo "::endgroup::"
)

for f in "${files[@]}"; do
  build-and-push "$f"
done
