#!/bin/bash

set -eux

CACHE="${PWD}/.buildx"
CACHE_NEW="${CACHE}-new"

files=(*/Dockerfile)

build-and-push() (
  image=$(dirname $1)
  cd "$image"

  docker buildx build \
    --pull \
    --push \
    --cache-from=type=local,src="${CACHE}/$image" \
    --cache-to=type=local,dest="${CACHE_NEW}/$image",mode=max \
    --platform linux/amd64,linux/arm64 \
    -t "wint/$image:latest" \
    .
)

mkdir -p "$CACHE"
mkdir -p "$CACHE_NEW"

set -x
for f in "${files[@]}"; do
  build-and-push "$f"
done

# https://github.com/moby/buildkit/issues/1896
mv "$CACHE" "${CACHE}-del" && ( rm -rf "${CACHE}-del" & ) # do not wait for deletion to complete
mv "$CACHE_NEW" "$CACHE"
