name: Build and push to docker hub

on:
  push:
    branches:
    - master
  schedule:
  - cron: "17 0 * * *" # every day at midnight jakarta time
  workflow_dispatch:
    inputs:
      skip-cache:
        type: boolean
        default: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: .buildx
        key: buildx-${{ github.sha }}
        restore-keys: buildx-
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - uses: docker/login-action@v3
      with:
        username: wint
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Run build and push script
      env:
        SKIP_CACHE: "${{ github.event.inputs.level && 'true' || 'false' }}"
      run: ./build-and-push
