name: Build and push to docker hub

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 0 * * 0" # every week

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - uses: docker/login-action@v3
      with:
        username: wint
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Run build and push script
      run: ./build-and-push
