name: Build and push to docker hub

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 17 * * 0" # every day at midnight jakarta time
  workflow_dispatch:
    inputs:
      skip-cache:
        type: string
        default: ""

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: .buildx
        key: buildx-${{ github.run_id }}-${{ github.run_number }}
        restore-keys: |
          buildx-${{ github.run_id }}-
          buildx-
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - uses: docker/login-action@v3
      with:
        username: wint
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Run build and push script
      env:
        SKIP_CACHE: "${{ github.event.inputs.skip-cache }}"
      run: ./build-and-push 2>&1
